<a href="https://colab.research.google.com/github/MinMint01/Basic-Python-for-ML/blob/main/Numpy_Library_%26_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## `Numpy`- Numerical Python

> The python library for basic array operations.

### Basics

This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## `NumPy` Array Attributes

First let's discuss some useful array attributes.

We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.

We'll use `NumPy`'s random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

### Loading `numpy` to a python programme

>Syntax 

```
import numpy as <<"name of instance">>

```

eg: ``` import numpy as np```

In [ ]:
# Loading the library
import numpy as np

# Installing a library in colab

```
!pip install <lib_name>
```

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Define different types of `numpy` arrays

In [ ]:
np.random.seed(0)  # seed for reproducibility  # starting point for generating random nums  # we lose randomness  # Used to check validity of samples
                        # Here '10' means take random nums under 10
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print(x1)

[5 0 3 3 7 9]


In [ ]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [ ]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


>Panel of matrices in Pandas -> Tensor in maths

## Attributes of arrays

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [ ]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)   # (x,)->Row Vector | (,x)->column vector
print("x1 size: ", x1.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6


In [ ]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``, the data type of the array

In [ ]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


## Array Indexing: Accessing Single Elements
If you are familiar with Python's standard list indexing, indexing in `NumPy` will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [ ]:
x1=np.array([8, 5, 4, 7,4,1]) # type cast list to np array

In [ ]:
(x1) # shows the contents of the array x1
print(x1)

[8 5 4 7 4 1]


In [ ]:
x1[3] # access the 4th element in the array x1

7

>Note:

To index from the end of the array, you can use negative indices:

In [ ]:
x1

array([8, 5, 4, 7, 4, 1])

In [ ]:
x1[-1] ## access the first element from last

1

In [ ]:
x1[-2] ## access the second element from the last

4

>In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [ ]:
x2=np.array([[3, 3, 9, 2],
       [5, 2, 3, 5],
       [7, 2, 7, 1]])

In [ ]:
print(x2)# list the 2-D array

[[3 3 9 2]
 [5 2 3 5]
 [7 2 7 1]]


In [ ]:
x2[0, 2] ## access the element in first row and first column

9

In [ ]:
x2[2, -1] ## access the element in the 3rd row and last column

1

Values can also be modified using any of the above index notation:

In [ ]:
x2[0, 0]=20 ## replace the 3rd row last column element of x2 by 20

In [ ]:
x2 ## display updated x2

array([[20,  3,  9,  2],
       [ 5,  2,  3,  5],
       [ 7,  2,  7,  1]])

> Keep in mind that, unlike Python lists, NumPy arrays have a `fixed type`.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [ ]:
## to show contents of the array x1
x1

array([8, 5, 4, 7, 4, 1])

In [ ]:
type(x1)  #datatype of obj 'x1'

numpy.ndarray

In [ ]:
x1.dtype  #datatype stored in the obj 'x1'

dtype('int64')

In [ ]:
## repalce first value of x1 with 3.14195
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 5, 4, 7, 4, 1])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [ ]:
x = np.arange(0,10) # gen array in the range 0-10, excluding 10
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[0:5]  # first five elements   # goes til n-1 = 6-1 = 5th index

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::2]  # every other element with step 2 (alternate elements)

array([0, 2, 4, 6, 8])

## Reading a 2-D array or matrix in `numpy`

```{python}
name_of_array=np.array([[row1],[row2],[row3]])
```

In [ ]:
marks=np.array([[1, 2 ,3],[2 ,3 ,4],[5,6,7]])

In [ ]:
print(marks)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [ ]:
C1=(marks[:,0]) # assign all elements in the first column to a new variable C1

In [ ]:
print(C1) # display content of C1 which is a sub array of marks

[1 2 5]


In [ ]:
type(C1)

numpy.ndarray

In [ ]:
marks[0,:]

array([1, 2, 3])

In [ ]:
print(C1)

[1 2 5]


In [ ]:
C2=C1.reshape(3,1)# reshape the list C1 into a 3 X 1 matrix

In [ ]:
(C2)  #F2 is the Transpose of matrix C1 but reshaping does not always gives the transpose
print(C2)

[[1]
 [2]
 [5]]


>**Task 1:** Create a $5\times 10$ matrix from single digit values randomly. Then flaten the matrix into a column vector.

In [ ]:
M=np.random.randint(10,size=(5,10))

In [ ]:
print(M)

[[4 3 4 4 8 4 3 7 5 5]
 [0 1 5 9 3 0 5 0 1 2]
 [4 2 0 3 2 0 7 5 9 0]
 [2 7 2 9 2 3 3 2 3 4]
 [1 2 9 1 4 6 8 2 3 0]]


In [ ]:
M.reshape(10,5) # not a transpose

array([[4, 3, 4, 4, 8],
       [4, 3, 7, 5, 5],
       [0, 1, 5, 9, 3],
       [0, 5, 0, 1, 2],
       [4, 2, 0, 3, 2],
       [0, 7, 5, 9, 0],
       [2, 7, 2, 9, 2],
       [3, 3, 2, 3, 4],
       [1, 2, 9, 1, 4],
       [6, 8, 2, 3, 0]])

In [ ]:
M.reshape(50,1) #flatten

array([[4],
       [3],
       [4],
       [4],
       [8],
       [4],
       [3],
       [7],
       [5],
       [5],
       [0],
       [1],
       [5],
       [9],
       [3],
       [0],
       [5],
       [0],
       [1],
       [2],
       [4],
       [2],
       [0],
       [3],
       [2],
       [0],
       [7],
       [5],
       [9],
       [0],
       [2],
       [7],
       [2],
       [9],
       [2],
       [3],
       [3],
       [2],
       [3],
       [4],
       [1],
       [2],
       [9],
       [1],
       [4],
       [6],
       [8],
       [2],
       [3],
       [0]])

In [ ]:
M.T #we get the transpose here

array([[4, 0, 4, 2, 1],
       [3, 1, 2, 7, 2],
       [4, 5, 0, 2, 9],
       [4, 9, 3, 9, 1],
       [8, 3, 2, 2, 4],
       [4, 0, 0, 3, 6],
       [3, 5, 7, 3, 8],
       [7, 0, 5, 2, 2],
       [5, 1, 9, 3, 3],
       [5, 2, 0, 4, 0]])



---


>**Flattening a matrix:**  Coverting a matrix into a colum vector.

---



In [ ]:
FM=marks.reshape(9,1)

In [ ]:
FM

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

### Multi-dimensional subarrays (slicing)

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [ ]:
# creating a two dimensional array
x2=np.array([[1,2,3],[3,4,5],[5,6,7]])

In [ ]:
print(x2)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [ ]:
# selecting first 3 rows and first two columns from x2
print(x2[:3:2,1:2])

[[2]
 [6]]


In [ ]:
print(x2[:3:2,:3:2]) # slice alternate elements in first three rows and first three columns

[[1 3]
 [5 7]]


>**Note:** Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

>For example *all the elements* in first column can be accessed as:

In [ ]:
print(x2[:, 0])  # first column of x2

[1 3 5]


### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [ ]:
x2

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [ ]:
# create a copy of subarray and store it with the new name
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[1 2]
 [3 4]]


If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  2]
 [ 3  4]]


In [ ]:
print(x2)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
grid = np.arange(1, 10).reshape((9, 1))
print(grid)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


>**Note:** Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

In [ ]:
x = np.array([1, 2, 3])

In [ ]:
print(x)

[1 2 3]


In [ ]:
x.shape

(3,)

In [ ]:
# row vector via reshape
x1=x.reshape((1, 3))

In [ ]:
x1.shape

(1, 3)

In [ ]:
print(x1)

[[1 2 3]]


In [ ]:
x

array([1, 2, 3])

In [ ]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
np.concatenate([y, y,y])

array([3, 2, 1, 3, 2, 1, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:





In [ ]:
grid1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid2=np.array([[5,5,5],[7,7,7]])

In [ ]:
# concatenate along the first axis
nm=np.concatenate([grid1, grid2],axis=0)

In [ ]:
nm.shape

(2, 6)

In [ ]:
# concatenate along the second axis (horrizontal) (zero-indexed)
np.concatenate([grid1, grid2], axis=1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 7, 7]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
grid2=np.vstack([grid,x])

In [ ]:
grid2

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99],[3]])


In [ ]:
grid2

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [ ]:
np.hstack([grid2, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99],
       [ 1,  2,  3,  3]])

## Splitting of arrays
The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

In [ ]:
import numpy as np # import numpy to use split function

> Now split the list into two sub lists at index 2

In [ ]:
x1,x2,x3=np.split(x,[2,4])

In [ ]:
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [ ]:
print(x1,"\n",x2,'\n',x3)

[1 2] 
 [ 3 99] 
 [99  3  2  1]


>**Notice:** that $N$ split-points, leads to $N + 1$ subarrays.

The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
left, right = np.hsplit(grid, [2])
print("Left array:\n",left,"\n Right array:\n",right)


Left array:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
 Right array:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Some important `numpy` function

In [ ]:
np.eye(3) #identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.ones((2,2)) # one matrix

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.diag([1,2,3]) #creating a diagonal matrix

array([[ 0, -1, -1],
       [-1,  1, -1],
       [-1, -1,  2]])

In [ ]:
np.diag(np.array([1,2,3])-1) # creating A-\lambda I

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [ ]:
np.diag([1,2,3])**2 # element-wise squaring

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

>**Task:** Create a $3\times 3$ matrix containing first 9 non-zero integres and find $A-3 I$ with `numpy` array operations.

>Task 1
Create a matrix, $A$ using `numpy`  and find the covariance , $cov(A)$ using matrix operation.

In [ ]:
# creating a random matrix
import numpy as np
A=np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

> Finding $A-\bar{A}$

In [ ]:
A_bar=np.mean(A,axis=1) # calculating row-wise sum
A_bar

array([ 1.5,  5.5,  9.5, 13.5])

In [ ]:
# creating a matrix to get element by element subtraction
np.outer(A_bar,np.ones(4))

array([[ 1.5,  1.5,  1.5,  1.5],
       [ 5.5,  5.5,  5.5,  5.5],
       [ 9.5,  9.5,  9.5,  9.5],
       [13.5, 13.5, 13.5, 13.5]])

In [ ]:
# calculating A-A bar with outer product opertation
(A-np.outer(A_bar,np.ones(4)))

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [ ]:
#calculating A-A_bar using broadcasting
X=A-np.mean(A,axis=1).reshape(4,1)

In [ ]:
X

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [ ]:
#mannualy calculating covariance
CoV=(1/3)*np.dot(X,X.T)
CoV

array([[1.66666667, 1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667, 1.66666667]])

In [ ]:
#calculating covariance using numpy function
np.cov(A)

array([[1.66666667, 1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667, 1.66666667]])

In [ ]:
#comparing two ways of flattening a matrix using numpy
A.reshape(-1)==A.reshape(16,)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])